### ISSUE TITLE
Linux Upload 

### ISSUE THREAD

**Issue by MoJoShMaN** [uhcs2320/hwZero#12]
problem uploading solved.

**Comment by aleman** [comment]
From the syllabus, download the file cs-and-ssh.docx (word document, direct link: [here](https://github.com/uhcs2320/syllabus/raw/master/cs-and-ssh.docx) ).
Recommended: read the whole thing before proceeding.

I'd suggest you use SSH instead of PUTTY in step 2.

The end of page 1 of the word document shows two icons of SSH, the first is equivalent to PUTTY.
The second icon is FTP for secure transferring of files.

Example of additional instructions for setting up SSH on a windows computer: [link](https://sils.unc.edu/it-services/servers/using-ssh) (no need to do the 'create profiles' steps listed there).

The SSH secure shell client mentioned, is one program with two parts, the command-line part, and the FTP part.
In order to move files from your computer to the linux server, and on Windows, then use the FTP icon. 
In order to use the command-line on the linux server, do it done via the other icon (not the FTP one).

The nice thing about that SSH client software having two parts, is that, if you're logged-in on the linux server and using the command-line, then clicking the yellow icon will open the FTP part for transferring files. This is figure 3 from the example instructions link listed above: ![Figure3](https://sils.unc.edu/sites/default/files/it/ssh_3.png).

**Comment by MoJoShMaN** [comment]
I have uploaded it correctly, even uploaded a test file, cpp, and an executable. but when i try to run it nothing happens, i did

[myusername@program hw0]$ g++ -std=c++11 -o uhday -I ./ *.cpp

and just got back to the input

[myusername@program hw0]$

what do i do to test this correctly?
I might add however, that when i check the directory, now there is a green uhday and i have no idea what that is

**Comment by aleman** [comment]
It looks that it compiled OK.
See the last step(s) listed [here](https://github.com/uhcs2320/syllabus/blob/master/Copy-to-linux-server.md) to test it.

**Comment by aleman** [comment]
I'm closing this but please don't hesitate to ask in case that something is still in need of an answer.
