### ISSUE TITLE
help on "input=FILENAME.txt" 

### ISSUE THREAD

**Issue by jknguyen914** [uhcs2320/hwZero#13]
![screen shot 2016-09-08 at 3 16 33 pm](https://cloud.githubusercontent.com/assets/21202086/18365263/9d7cae48-75d7-11e6-8b6a-3832f824e80a.jpg)

I have the problem with parameter input , can anyone show me how to do it ? , i did follow the one post on on here by professor but received an error.

**Comment by MoJoShMaN** [comment]
I completely copied his parameter code into my code, then changed the ifstream to get the variable filename and now mines working with parameters, ex in cmd prompt  
.....uhday.exe parameter="example.txt"

**Comment by amonjaraz** [comment]
I just tried what you posted and it worked. How are you running your program?

**Comment by MoJoShMaN** [comment]
just through the command prompt bc im on windows. i compile in visual studio first though

**Comment by amonjaraz** [comment]
Okay, I just switched over to windows and it is working for me using the "Developer Command Prompt for VS2015"

Try following this example for compiling and running : https://msdn.microsoft.com/en-us/library/ms235639.aspx

**Comment by MoJoShMaN** [comment]
I got it to compile in cmd prompt, I need help making it compile whilst in the linux server. The example he gave us created a green file in my hw0 folder, but idk if thats output or what and i cant seem to access it. but if I check the dir, its sitting there lol.

**Comment by amonjaraz** [comment]
I saw that you tried 
`[myusername@program hw0]$ g++ -std=c++11 -o uhday -I ./ *.cpp`
which is how you compile on linux. If it compiles successfully , you can then try
`[myusername@program hw0]$ ./uhday "input=filename.txt"`
Make sure your input file is in the same directory for it to run correctly.

**Comment by jknguyen914** [comment]
Well i did the following ./uhday "input=gray.txt" 
And nothing showup on the screen

**Comment by jknguyen914** [comment]
And I did upload/copy gray.txt into hw0 folder

**Comment by jknguyen914** [comment]
![screen shot 2016-09-08 at 7 15 20 pm](https://cloud.githubusercontent.com/assets/21202086/18371277/a538603e-75f8-11e6-8f8d-7b0f9cf88f8b.jpg)
![screen shot 2016-09-08 at 7 14 54 pm](https://cloud.githubusercontent.com/assets/21202086/18371278/a6c89036-75f8-11e6-801b-2158ad09be08.jpg)
did is what I get from terminal

**Comment by Akshay199456** [comment]
I will explain what worked for me.
- Copied the code from Param.cpp into my main method.
- Passed the parameter filename in param.cpp into the method that reads the file ( or you could also directly pass this into the ifstream object. Also make sure to comment the output from the param.cpp file ).

![image](https://cloud.githubusercontent.com/assets/11953567/18371068/4ef25dde-75f7-11e6-80fd-6396ffaef69c.png)
- Made sure that the test files were stored in the hw0 directory of the server and modified the names of the file

![image](https://cloud.githubusercontent.com/assets/11953567/18371129/9250d538-75f7-11e6-8026-1bec18ffcfa4.png)

---

The section below will be an explanation of what the code in param.cpp does:

The command 

![image](https://cloud.githubusercontent.com/assets/11953567/18371364/7016649a-75f9-11e6-842f-63e93189a841.png)

in param.cpp stores everything from the position 10 of the string "parameter" into the string "filename". In this example, 

parameter= 
![image](https://cloud.githubusercontent.com/assets/11953567/18371487/3f8d68b8-75fa-11e6-8889-deb4a35ffeea.png)

filename=
"![image](https://cloud.githubusercontent.com/assets/11953567/18371500/587fed5a-75fa-11e6-81d3-099fafcbb574.png)"

Since you are now passing ![image](https://cloud.githubusercontent.com/assets/11953567/18371500/587fed5a-75fa-11e6-81d3-099fafcbb574.png)   into the method that reads the file, it checks for that file in the cwd of the hw0 folder in the server. 

---

Since it finds that file in hw0 folder , it should give you the desired output as follows ( output for 1-a.input1 ):

![image](https://cloud.githubusercontent.com/assets/11953567/18371638/819999ec-75fb-11e6-89bf-8c149ce40028.png)

Hope that helps...

---

## Edit:

If you change the "parameter" string from 
![image](https://cloud.githubusercontent.com/assets/11953567/18373088/d0585bd0-7606-11e6-8d09-352197416bfd.png)

  to ![image](https://cloud.githubusercontent.com/assets/11953567/18373082/bd5d943c-7606-11e6-87fa-ea7043f75dfc.png)

the "filename" parameter will now accept the substring from the first character after the equal sign ( in ![image](https://cloud.githubusercontent.com/assets/11953567/18373117/0f22f6d6-7607-11e6-9024-353dee46138e.png) ) till the end of the string. This will prevent the additional step of having to rename the file again. You would be able to directly upload the file to the server and compile and run it.

**Comment by jknguyen914** [comment]
what command did you use to upload the test case on github to the terminal ?
is it gw or get ?

**Comment by Akshay199456** [comment]
I uploaded the test cases on Github into the server using the scp command ( the same command to copy the uhday.cpp file into the server ).

**Comment by jknguyen914** [comment]
thanks . finally got it :)

**Comment by aleman** [comment]
I'm closing this but please don't hesitate to ask in case that something is still in need of an answer.
